openapi: "3.0.1"
info:
  title: Payments API definition
  version: v0
servers:
  - url: http://localhost:8081/cash-account-management/v1
    description: Generated server url

paths:

  /payment/{accountId}/money-transfers:
    post:
      summary: Insert a new money transfer
      operationId: createMoneyTransfer
      tags:
        - Payment
      parameters:
        - name: accountId
          in: path
          schema:
            type: string
          required: true
      requestBody:
        description: create money transfer dto
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MoneyTransferDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateMoneyTransferResource'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found

components:
  schemas:


    MoneyTransferDTO:
      type: object
      required:
        - receiverName
        - description
        - currency
        - amount
      properties:
        receiverName:
          type: string
        description:
          type: string
        currency:
          type: string
        amount:
          type: string
        executionDate:
          type: string
          format: date


    CreateMoneyTransferResource:
      type: object
      properties:
        status:
          type: string
